import type { Theme, TypographyOptions } from "../model/types"
import {
  buildReadingStyleCssVariables,
  buildReadingStyleProfile
} from "./reading-style-profile"

export function buildDomChapterNormalizationCss(input: {
  theme: Theme
  typography: TypographyOptions
  fontFamily: string
  renditionLayout?: "reflowable" | "pre-paginated"
  presentationRole?: "cover" | "image-page"
}): string {
  const profile = buildReadingStyleProfile({
    theme: input.theme,
    typography: input.typography
  })
  const variables = buildReadingStyleCssVariables(profile)

  return [
    `.epub-dom-section {`,
    `  color: ${input.theme.color};`,
    `  background: transparent;`,
    `  display: flow-root;`,
    `  font-family: ${input.fontFamily};`,
    `  font-size: ${input.typography.fontSize}px;`,
    `  line-height: ${input.typography.lineHeight};`,
    `  letter-spacing: var(--reader-letter-spacing);`,
    `  word-spacing: var(--reader-word-spacing);`,
    ...Object.entries(variables).map(([name, value]) => `  ${name}: ${value};`),
    `  padding: 0 var(--reader-side-padding) var(--reader-bottom-padding);`,
    `  box-sizing: border-box;`,
    `}`,
    `.epub-dom-section-fxl {`,
    `  padding: 0;`,
    `  width: var(--fxl-render-width, var(--fxl-viewport-width, 100%));`,
    `  min-height: var(--fxl-render-height, var(--fxl-viewport-height, auto));`,
    `  aspect-ratio: var(--fxl-viewport-width, 1) / var(--fxl-viewport-height, 1);`,
    `  margin: 0 auto;`,
    `  overflow: hidden;`,
    `}`,
    `.epub-dom-section[dir="rtl"] {`,
    `  direction: rtl;`,
    `}`,
    `.epub-dom-cover, .epub-dom-image-page {`,
    `  padding: 0;`,
    `  width: 100%;`,
    `  max-width: var(--reader-presentation-width, 100%);`,
    `  height: var(--reader-presentation-height, auto);`,
    `  min-height: var(--reader-presentation-height, auto);`,
    `  display: flex;`,
    `  align-items: center;`,
    `  justify-content: center;`,
    `  overflow: hidden;`,
    `}`,
    `.epub-dom-section :where(p, blockquote, pre, ul, ol, dl, table, figure, aside, nav) {`,
    `  margin-top: 0;`,
    `  margin-bottom: var(--reader-paragraph-spacing);`,
    `}`,
    `.epub-dom-section :where(h1, h2, h3, h4, h5, h6) {`,
    `  margin-top: 0;`,
    `  margin-bottom: var(--reader-heading-spacing);`,
    `  line-height: 1.25;`,
    `}`,
    `.epub-dom-section a {`,
    `  color: var(--reader-link-color);`,
    `}`,
    `.epub-dom-section mark {`,
    `  background: var(--reader-mark-bg);`,
    `  color: inherit;`,
    `}`,
    `.epub-dom-section blockquote {`,
    `  margin-left: 0;`,
    `  margin-right: 0;`,
    `  padding-left: var(--reader-quote-accent-gap);`,
    `  border-left: var(--reader-quote-accent-width) solid var(--reader-quote-accent-color);`,
    `}`,
    `.epub-dom-section[dir="rtl"] blockquote {`,
    `  padding-left: 0;`,
    `  padding-right: var(--reader-quote-accent-gap);`,
    `  border-left: 0;`,
    `  border-right: var(--reader-quote-accent-width) solid var(--reader-quote-accent-color);`,
    `}`,
    `.epub-dom-section aside {`,
    `  background: var(--reader-aside-bg);`,
    `  padding: 8px 12px;`,
    `  border-radius: 12px;`,
    `}`,
    `.epub-dom-section figure {`,
    `  margin-left: 0;`,
    `  margin-right: 0;`,
    `}`,
    `.epub-dom-section figcaption, .epub-dom-section caption {`,
    `  margin-top: var(--reader-caption-margin-top);`,
    `  color: var(--reader-caption-color);`,
    `  font-size: var(--reader-caption-font-size);`,
    `  line-height: var(--reader-caption-line-height);`,
    `  font-style: italic;`,
    `}`,
    `.epub-dom-section ul, .epub-dom-section ol {`,
    `  padding-left: calc(var(--reader-side-padding) + 28px);`,
    `}`,
    `.epub-dom-section[dir="rtl"] ul, .epub-dom-section[dir="rtl"] ol {`,
    `  padding-left: 0;`,
    `  padding-right: calc(var(--reader-side-padding) + 28px);`,
    `}`,
    `.epub-dom-section dt {`,
    `  font-weight: 700;`,
    `}`,
    `.epub-dom-section dd {`,
    `  margin-left: calc(var(--reader-side-padding) + 20px);`,
    `}`,
    `.epub-dom-section[dir="rtl"] dd {`,
    `  margin-left: 0;`,
    `  margin-right: calc(var(--reader-side-padding) + 20px);`,
    `}`,
    `.epub-dom-section img {`,
    `  max-width: 100%;`,
    `  height: auto;`,
    `  display: block;`,
    `  margin: 0 auto;`,
    `}`,
    `.epub-dom-cover .epub-dom-presentation-image, .epub-dom-image-page .epub-dom-presentation-image {`,
    `  display: block;`,
    `  width: auto;`,
    `  height: auto;`,
    `  max-width: 100%;`,
    `  max-height: 100%;`,
    `  object-fit: contain;`,
    `  margin: 0 auto;`,
    `}`,
    `.epub-dom-section table {`,
    `  width: 100%;`,
    `  border-collapse: collapse;`,
    `}`,
    `.epub-dom-section caption {`,
    `  caption-side: bottom;`,
    `  text-align: left;`,
    `}`,
    `.epub-dom-section[dir="rtl"] caption {`,
    `  text-align: right;`,
    `}`,
    `.epub-dom-section th, .epub-dom-section td {`,
    `  border: 1px solid var(--reader-table-border-color);`,
    `  padding: var(--reader-table-cell-padding);`,
    `  vertical-align: top;`,
    `  text-align: left;`,
    `}`,
    `.epub-dom-section pre, .epub-dom-section code {`,
    `  font-family: ${profile.code.fontFamily};`,
    `}`,
    `.epub-dom-section pre {`,
    `  white-space: pre-wrap;`,
    `  background: var(--reader-code-bg);`,
    `  color: var(--reader-code-color);`,
    `  padding: ${profile.code.blockPaddingY}px ${profile.code.blockPaddingX}px;`,
    `  border-radius: ${profile.code.blockRadius}px;`,
    `}`,
    `.epub-dom-section code {`,
    `  color: var(--reader-inline-code-color);`,
    `}`,
    `.epub-dom-section :not(pre) > code, .epub-dom-section .code-fragment {`,
    `  background: var(--reader-inline-code-bg);`,
    `  padding: ${profile.code.inlinePaddingY}px ${profile.code.inlinePaddingX}px;`,
    `  border-radius: ${profile.code.inlineRadius}px;`,
    `}`,
    `.epub-dom-section hr {`,
    `  border: 0;`,
    `  border-top: var(--reader-rule-width) solid var(--reader-rule-color);`,
    `  margin: var(--reader-paragraph-spacing) 0;`,
    `}`,
    `.epub-dom-section pre code {`,
    `  background: transparent;`,
    `  padding: 0;`,
    `}`
  ].join("\n")
}
